### ISSUE TITLE
DBPF module does not decompress properly

### ISSUE THREAD

**Issue by lah7** [lah7/sims2-4k-ui-mod#1]
This is documented at the URLs:

* https://simswiki.info/index.php?title=E86B1EEF
* https://simswiki.info/index.php?title=DBPF_Compression
* https://simswiki.info/wiki.php?title=DBPF

I had trouble understanding where within the DBPF file (binary) to process this.

Currently, we must depend on SimPE to extract the files. It would be excellent to process the original `ui.package` without relying on SimPE and manual steps.

**Comment by lah7** [comment]
For reference, here's the C# implementation in SimPE:

https://github.com/simtactics/SimPE/blob/master/fullsimpe/SimPe%20Packages/PackedFile.cs#L678-L775

**Comment by lingeringwillx** [comment]
I've managed to write bindings to a C library to compress and decompress the package entries in my own DBPF library. You can take a look at it [here](https://github.com/lingeringwillx/sims2lib) .

Also, in the past I managed to write decompression code in pure Python just by mimicking the [PHP code](https://simswiki.info/index.php?title=DBPF_Compression) in the sims wiki, but the C bindings are significantly faster.

**Comment by lah7** [comment]
Thanks - great timing! I did make a breakthrough the other week _(and just pushed now)_ as I used GitHub Copilot (AI) to assist with porting a Java implementation of the algorithm (code is under GPLv3 too).
https://github.com/memo33/jDBPFX

This sort of low level processing is new to me, but it was a bit of a nice challenge. I couldn't find an existing Python module that was Python 3 compatible; supported QFS {de}compression; was under a compatible FOSS license or were easy to use.

Decompression works - albeit probably won't be as fast as C, but speed is not the priority. This means I can begin building a UI and logic to automate the upscaling process -- **but first,** I'm attempting the compression side as well (#2), as I wonder if this will "improve" any of the weird bugs so far. I'll take a look at your C implementation as it may help me figure out [why it's not working right now:](https://github.com/lah7/sims2-4k-ui-mod/blob/wip-decompression/qfs.py)

**Comment by lingeringwillx** [comment]
Cool! Keep in mind that the C code isn't mine. I only adjusted it slightly and wrote the Python bindings.

Yeah, compression does seem more difficult than decompression. That's why I went with the option of writing bindings to an existing library.
