### ISSUE TITLE
Implement QFS compression for DBPF package

### ISSUE THREAD

**Issue by lah7** [lah7/sims2-4k-ui-mod#2]
The end result are some pretty large `ui.package` files. After figuring out #1, it would be ideal to support the compression of the new `ui.package` file.

**Comment by lah7** [comment]
Using a GPLv3 Java implementation (thanks!), I had an attempt at a pure Python implementation. It's [currently in the `wip-decompression` branch](https://github.com/lah7/sims2-4k-ui-mod/blob/wip-decompression/qfs.py#L97) and it's not quite working right now.

* https://github.com/lah7/sims2-4k-ui-mod/commit/3a0460fcb81d367e4cb3e5fe007ee3c8b73d67db

To test  (this is for Linux/WSL):
```bash
export PYTHONPATH=$(pwd)
```

```python
import dbpf
import qfs

package = dbpf.DBPF("ui.package")
entry = package.index.entries[16]  # A random TGA file

# Extract to file
package.extract(entry, "/tmp/original.tga")

# Compress that file 
data = open("/tmp/original.tga", "rb").read()
cdata = qfs.compress(bytearray(data))
with open("/tmp/compressed.tga.qfs", "wb") as f:
    f.write(cdata)

# Test it can decompress and match the original - NOT WORKING
print("Compressed size:", len(cdata), "bytes")
print("Decompressed size:", len(data), "bytes")
ddata = qfs.decompress(bytearray(cdata), len(data))
with open("/tmp/new.tga", "wb") as f:
    f.write(ddata)
```

**Comment by memo33** [comment]
This looks pretty good. I've added a few remarks to commit https://github.com/lah7/sims2-4k-ui-mod/commit/3a0460fcb81d367e4cb3e5fe007ee3c8b73d67db.

**Comment by lah7** [comment]
Thank you for reviewing, much appreciated! Learnt something new about the[ `//` operator.](https://docs.python.org/release/2.2.3/whatsnew/node7.html). 
* db3b1d87136bc8228d7a66946297397ba78f372a

An original, uncompressed TGA file and one that was decompressed after going through this compression are byte-for-byte perfect, that's great. 👍🏼  

The last issue remaining is that the compressed data is 135 bytes longer than the decompressed data. In a hex editor, I can see a lot of `00 FF 00 FF 00 FF 00 FF` throughout the file - might have to debug line by line to figure out what causes that.

**Comment by memo33** [comment]
Try it like this:
```diff
     # Begin main compression loop
-    while True:
-        index += 1
-
-        if index >= last_read_index:
-            break
-
+    while index < len(data) - 3:
+      while True:
         # Get all compression candidates
         # (list of offsets for all occurrences of the current 3 bytes)
+        index += 1
         if index >= len(data) - 2:
             end = True
             break
         map_index: int = (data[index] & 0xFF) | ((data[index + 1] & 0xFF) << 8) | ((data[index + 2] & 0xFF) << 16)

         index_list: list = cmpmap2.get(map_index) or []
         if not index_list:
             cmpmap2[map_index] = index_list
         index_list.append(index)
-        if index >= last_read_index or end:
+        if index >= last_read_index:
             break
+      if end:
+        break
```
Two nested while loops are needed. (I've indented by just 2 spaces for clarity of the diff.)

**Comment by lah7** [comment]
Excellent! That did the trick, thank you!

**Comment by memo33** [comment]
One more change would be needed to make the code equivalent to the Java code.
```diff
diff --git a/qfs.py b/qfs.py
index e19124c..537623f 100644
--- a/qfs.py
+++ b/qfs.py
@@ -125,7 +125,7 @@ def compress(data: bytearray) -> bytes:
     while index < len(data) - 3:
         # Get all compression candidates
         # (list of offsets for all occurrences of the current 3 bytes)
-        while not end:
+        while True:
             index += 1
             if index >= len(data) - 2:
                 end = True
@@ -139,6 +139,8 @@ def compress(data: bytearray) -> bytes:
             index_list.append(index)
             if index >= last_read_index:
                 break
+        if end:
+            break

         # Find the longest repeating byte sequence in the index list (for offset copy)
         offset_copy_count = 0
```

**Comment by lah7** [comment]
Thanks. Both are technically correct. I opted for `while not end` so it's a bit easier to read the condition (and use of `end`) for anyone new (or myself) looking at the code later.

**Comment by memo33** [comment]
The intention behind the `end` flag is to break out of both loops, but with 1b32252ba1c53472e1445674e500c5ad108053a2 you only break from the inner loop -- not the outer loop.

**Comment by lah7** [comment]
Understood, corrected. Will also commit some unit tests in future.
